#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
tpf-switchboard creates and destroys udp proxies dynamically on request.
"""

import time
import proxies

def main():
    try:
        my_proxy = proxies.SimpleProxy(listen_port=4444)
        my_proxy.start()
        time.sleep(10)
        print('Jetzt wollen wir aufhören')
        my_proxy.stop()
        print('Bis hier mussten wir warten')
    except KeyboardInterrupt:
        sys.exit(0)

if __name__ == '__main__':
        main()

