#!/usr/bin/env python3
"""udp_mirror relays any incoming packet back to the sender, that simple.
"""

import socket
import sys

UDP_IP = "0.0.0.0"

def main():
    try:
        UDP_PORT = int(sys.argv[1])
    except ValueError:
        sys.stderr.write('Specified port is not a number\n')
        sys.exit(1)

    # haben wir einen gueltigen Port
    if not isinstance( UDP_PORT, int ) or not  1024 <= UDP_PORT <= 40000:
        sys.stderr.write('Specified port "%s" is invalid.\n' % UDP_PORT)
        sys.stderr.write('Valid port range: 1024 - 40000)\n')
        sys.exit(1)

    # Lass uns die socket erzeugen
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.bind((UDP_IP, UDP_PORT))
    except socket.error as msg:
        sys.stderr.write("[ERROR] %s\n" % msg[1])
        sys.exit(1)

    while True:
        try:
            data, addr = sock.recvfrom(65536)
            sock.sendto(data, addr)
        except KeyboardInterrupt:
            sys.exit(0)

if __name__ == '__main__':
    main()
